const APP_SET_USER = "APP_SET_USER";
const APP_ADD_LOADING = "APP_ADD_LOADING";
const APP_DELETE_LOADING = "APP_DELETE_LOADING";
const types = { APP_SET_USER, APP_ADD_LOADING, APP_DELETE_LOADING };

export default types;
