const AUTH_LOADING_START = "LOGIN_START";
const AUTH_FETCH_ERROR = "LOGIN_ERROR";
const AUTH_FETCH_SUCCESS = "LOGIN_SUCCESS";
const AUTH_SET_USER = "AUTH_SET_USER";
const AUTH_SET_FIRSTRUN = "AUTH_SET_FIRSTRUN";

const types = {
  AUTH_LOADING_START,
  AUTH_FETCH_ERROR,
  AUTH_FETCH_SUCCESS,
  AUTH_SET_USER,
  AUTH_SET_FIRSTRUN
};

export default types;
